Module1 task3
htmlacademy-ecmascript/1791339-big-trip-15 pull request #3
Opened 2021-07-28 21:20 UTC by ValeriaKhristinina

2021-07-28 21:45 UTC, AlexMasterov requested changes

2021-07-28 21:45 UTC, AlexMasterov commented on src/main.js
> +const triPListItem = document.querySelector('.trip-events__item');
tri`P`ListItem

[`Б 3`](https://up.htmlacademy.ru/ecmascript/15/criteries#b3)
> Название переменных, параметров, свойств и методов начинается со строчной буквы и записываются в нотации `camelCase`

2021-07-28 21:45 UTC, AlexMasterov commented on src/main.js
> +import { createTripInfo } from './view/trip-info.js';
<details>
<summary>webpack.config.js</summary>

https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/44956ed56bfdb8e2d05a66c0cf2a872795aebc75/webpack.config.js#L17-L19
</details>

`alias` был частично добавлен, но не используется.

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/44956ed56bfdb8e2d05a66c0cf2a872795aebc75/src/main.js#L1
</details>

См. https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/pull/2#discussion_r676955708.

Пример:
```diff
- import { createTripInfo } from './view/trip-info.js';
+ import { createTripInfo } from '@view/trip-info';
```

2021-07-28 21:45 UTC, AlexMasterov commented on src/main.js
> +  render(triPListItem, createEvent(), 'beforeend');
<details>
<summary>Ожидание (markup\list.html)</summary>

![image](https://user-images.githubusercontent.com/700213/127399219-720a510e-c5a3-4a2b-b175-e6fe972a3c07.png)

</details>

<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/127399198-ef819e1a-ae91-4c33-bafd-7c3642a62421.png)

</details>

Нужно в соответствие с макетом исправить разметку точек маршрута.

2021-07-28 21:45 UTC, AlexMasterov commented on src/main.js
> +render(tripEvents, creatingEditTripForm(), 'afterbegin');
<details>
<summary>Ожидание (markup/edit-point.html)</summary>

![image](https://user-images.githubusercontent.com/700213/127399709-f85ca0ce-41b3-45e0-a843-cf050dbdc6ca.png)
</details>

<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/127399840-3e659042-1e88-4dfd-b597-6e7887bdfddd.png)
</details>

Нужно в соответствие с макетом исправить разметку секции сортировки и формы редактирования.

2021-07-28 21:45 UTC, AlexMasterov commented on src/main.js
> +import { creatingEditTripForm } from './view/edit-trip-form.js';
<details>
<summary>view/new-trip-form.js</summary>

https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/44956ed56bfdb8e2d05a66c0cf2a872795aebc75/src/view/new-trip-form.js#L97
</details>
<details>
<summary>view/edit-trip-form.js</summary>

https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/44956ed56bfdb8e2d05a66c0cf2a872795aebc75/src/view/edit-trip-form.js#L97-L100
</details>

Обрати внимание на _ключевые_ отличия разметки формы редактирования и формы создания новой точки маршрута. В остальном разметка совпадает.

Советую подумать над решением, которое позволит переиспользовать _один_ шаблон с разметкой для разный режимов.

2021-07-28 21:45 UTC, AlexMasterov commented on src/main.js
> +
<details>
<summary>view/trip-list-empty.js</summary>

https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/44956ed56bfdb8e2d05a66c0cf2a872795aebc75/src/view/trip-list-empty.js#L2
</details>

<details>
<summary>view/loading-state.js</summary>

https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/44956ed56bfdb8e2d05a66c0cf2a872795aebc75/src/view/loading-state.js#L2
</details>

Разметка шаблонов отличается только текстом сообщения.

2021-07-30 07:29 UTC, ValeriaKhristinina commented on src/main.js
> +const triPListItem = document.querySelector('.trip-events__item');
😅

2021-07-30 19:52 UTC, merged