Module2 task1
htmlacademy-ecmascript/1791339-big-trip-15 pull request #4
Opened 2021-08-06 14:36 UTC by ValeriaKhristinina

Мне уже страшно ждать ответ😁

2021-08-06 16:28 UTC, AlexMasterov requested changes

2021-08-06 16:28 UTC, AlexMasterov commented on src/view/event.js
> +  return `<li class="trip-events__item">
<details>
<summary>view/event.js</summary>

https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/41f97cec72f1a3af681764e75577ea68cbf48c90/src/view/event.js#L19
https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/41f97cec72f1a3af681764e75577ea68cbf48c90/src/view/event.js#L26
https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/41f97cec72f1a3af681764e75577ea68cbf48c90/src/view/event.js#L28
</details>

Для атрибута `datetime` нужно использовать значение даты в формате `ISO`.

> См. тренажер: [Тег time, дата и время](https://htmlacademy.ru/courses/301/run/15) и [Date.p.`toISOString`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) (= [ISO 8601](https://ru.wikipedia.org/wiki/ISO_8601))

2021-08-06 16:28 UTC, AlexMasterov commented on src/view/event.js
>        <button class="event__favorite-btn event__favorite-btn--active" type="button">
<details>
<summary>Проблема</summary>

```js
tripPoints[4].isFavorite = false
```
![image](https://user-images.githubusercontent.com/700213/128539537-ad809c47-8fcc-49bd-b8e1-dbb12ec16837.png)

</details>

Сейчас все точки маршрута отображаются, как добавленные в избранное, хотя в данных точки маршрута `isFavorite = false`.

См. ТЗ:
> Кнопка «Favorite» (отображается в виде звёздочки). Добавляет точку маршрута в избранное. **После добавления в избранное, кнопка меняет состояние — яркая звезда**

Нужно в шаблоне использовать значение из данных: `point.isFavorite`.

2021-08-06 16:28 UTC, AlexMasterov commented on src/view/event.js
> +        <p class="event__duration">${time.duration}M</p>
`${time.duration}M`

Сейчас формат длительности показывает одинаковые значения, при этом использует только минуты и не учитывает разряды.

> Текущие тест. данные не помогают в реализации ТЗ

См. ТЗ:
>  Формат продолжительности нахождения в точке маршрута зависит от длительности:

> Менее часа: минуты (например, `23M`);
> Менее суток: часы минуты (например, `02H 44M` или `12H 00M`, если минуты равны нулю);
> Более суток: дни часы минуты (например, `01D 02H 30M` или `07D 00H 00M`, если часы и/или минуты равны нулю)

Нужно постараться доработать в этом задание.

2021-08-06 16:28 UTC, AlexMasterov commented on src/view/trip-form.js
> +            ${creatingEventTypeTemplate(TYPE_POINT, price)}
${creatingEventTypeTemplate(TYPE_POINT, `price`)}

Функция `creatingEventTypeTemplate` принимает только один аргумент:

https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/41f97cec72f1a3af681764e75577ea68cbf48c90/src/view/trip-form.js#L21

[`Б 18`](https://up.htmlacademy.ru/ecmascript/15/criteries#b18)
> В коде проекта нет файлов и частей кода, которые не используются, включая закомментированные участки кода

2021-08-06 16:28 UTC, AlexMasterov commented on src/view/trip-form.js
> +const creatingEventTypeTemplate = (types) => types.map((type) => `<div class="event__type-item">
<details>
<summary>Ожидание (markup/add-new-point.html)</summary>

![image](https://user-images.githubusercontent.com/700213/128532541-efe1b9b0-05ce-4190-b846-14abbd3e98b1.png)

</details>

<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/128532467-cba27ccf-996b-45f3-98a4-a6d4fb9abb3f.png)

</details>

В шаблоне списка типов типы из данных должны отображаться с заглавной буквы (= в верхнем регистре).

2021-08-06 16:28 UTC, AlexMasterov commented on src/mock/trip-point.js
> +const generateTripPoint = () => ({
<details>
<summary>mock/trip-point.js</summary>

https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/41f97cec72f1a3af681764e75577ea68cbf48c90/src/mock/trip-point.js#L40-L41
</details>

Данные с сервера не нужно подстраивать и дублировать под отображения в отдельных шаблонах; типы их значений должны быть пригодны для реализации _логики_. 

Например, каким образом будет реализована сортировка дат, если их значения _строки_? Как вычислить длительность на основе двух дат, если их значения _строки_? И т.д.

> На текущем интенсиве структуры данных с сервера доступны для изучения сразу, не дожидаясь открытия задания. См. [ТЗ 1.9.1 Ресурсы](https://up.htmlacademy.ru/ecmascript/15/project/big-trip#resource)

2021-08-06 16:28 UTC, AlexMasterov commented on src/view/trip-route.js
> +  const stringCities = cities.join(' &mdash; ');
`string`Cities

Б9

2021-08-07 20:28 UTC, ValeriaKhristinina commented on src/mock/trip-point.js
> +const generateTripPoint = () => ({
Я запушила, можешь посмотреть этот момент?

2021-08-07 20:35 UTC, ValeriaKhristinina commented on src/view/trip-form.js
> +export const creatingTripForm = (mode, point = {}) => {
В дизайне вроде нет данных у стоимости
<img width="1109" alt="Screenshot 2021-08-07 at 22 34 17" src="https://user-images.githubusercontent.com/20569123/128613232-7c6c734b-9437-4ef6-8342-932c2f0fd8c4.png">

2021-08-07 20:55 UTC, AlexMasterov commented on src/mock/trip-point.js
> +const generateTripPoint = () => ({
> Я запушила, можешь посмотреть этот момент?

Если речь про использование дат, то `dayjs` справится с логикой 😃

2021-08-09 10:12 UTC, ValeriaKhristinina commented on src/view/trip-form.js
> +import { TYPE_POINT, allOffers , DESTINATION } from '@/mock/trip-point';
Ну тогда в след и исправим🙃😁

2021-08-09 18:02 UTC, AlexMasterov commented
Молодец 👍🏻

2021-08-09 18:02 UTC, merged