Революция или эволюция? (часть 1)
htmlacademy-ecmascript/1791339-big-trip-15 pull request #5
Opened 2021-08-12 09:03 UTC by ValeriaKhristinina

---
:mortar_board: [Революция или эволюция? (часть 1)](https://up.htmlacademy.ru/ecmascript/15/user/1791339/tasks/5)

2021-08-12 10:11 UTC, AlexMasterov requested changes

2021-08-12 10:11 UTC, AlexMasterov commented on src/view/trip-form.js
> +  const editOffers = allOffers.map((generalOffer) => {
<details>
<summary>view/trip-form.js</summary>

https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/5b58f44ad29d9177e628977f252432312430b16a/src/view/trip-form.js#L37-L44
</details>

Повторю, что на сервере выбранные `offers` в точках маршрута и доступные `offers` генерируется по отдельности. Поэтому в выбранных `offers`, например, для типа `taxi`, могут быть предложения, которых нет в `offers` для то во же типа `taxi`. Также могут быть одинаковые предложения по названию, но с разной ценой.

Сейчас не учитывается обе ситуации: выбранные предложения, которых нет в доступных `offers` просто не отобразятся, а после редактирования точки вообще удаляться (теряем данные пользователя); к выбранному предложению добавится как `checked` невыбранное из доступных, если только их названия совпадают (добавляем одинаковое предложения пользователю, но с другой ценой).

> Если удалить все созданные на сервере точки маршрута, то проблему можно не заметить

> В свое время А.Сушко объяснил это имитацией "рыночной ситуации" и были планы добавить требование в ТЗ, но потом проект встал на путь упрощения, а проблема осталась

> На защите это никто не проверяет

2021-08-13 08:17 UTC, ValeriaKhristinina commented on src/utils.js
> +  const newElement = document.createElement('div');
До сих пор не понимаю, что у меня не так

2021-08-13 08:18 UTC, ValeriaKhristinina commented on src/utils.js
> +  const newElement = document.createElement('div');
<img width="375" alt="Screenshot 2021-08-13 at 10 16 14" src="https://user-images.githubusercontent.com/20569123/129326671-6553f8b8-9eed-4238-8aa3-9ef17fc71c1c.png">

2021-08-13 10:42 UTC, AlexMasterov commented on src/utils.js
> +  const newElement = document.createElement('div');
> До сих пор не понимаю, что у меня не так

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/b27995a2564a76a6fc5d5ce598053a0bf89a8a26/src/main.js#L22-L26
</details>

Например, в этом месте [document.`querySelector`](https://developer.mozilla.org/ru/docs/Web/API/Document/querySelector) возвращает DOM-элемент (= объект типа [`Element`](https://developer.mozilla.org/ru/docs/Web/API/Element), который сохраняется в переменные:

```js
tripMain instanceof Element               // true
tripControlsNavigation instanceof Element // true
tripControlsFilters instanceof Element    // true
pageMain instanceof Element               // true
tripEvents instanceof Element             // true
```

Но чтобы это показать (hint) в их название не используется суффикс `*Element`.

<details>
<summary>utils.js</summary>

https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/b27995a2564a76a6fc5d5ce598053a0bf89a8a26/src/utils.js#L25
</details>

В этом месте [document.`createElement`](https://developer.mozilla.org/ru/docs/Web/API/Document/createElement) тоже возвращает DOM-элемент и сохраняет в переменную. Но здесь переменная уже использует суффикс `*Element`.

Доп. критерий [`Д 6`](https://up.htmlacademy.ru/ecmascript/15/criteries#d6) требует _единообразия_ в именовании:
> Используется единый стиль именования переменных

> если есть переменные, которые хранят [DOM-элемент](https://developer.mozilla.org/ru/docs/Web/API/Element) и содержат слово `Element`, **то это правило работает везде**

Проблема в том, что функция `createElement` была заимствована из демо проекта без изменений и потому без учета, что в демо проекте этот суффикс используется во всем проекте (за исключения "нарушений" в [этом месте](https://github.com/htmlacademy-ecmascript/taskmanager-15/blob/module-2/src/main.js#L41) и [параметров функций](https://github.com/htmlacademy-ecmascript/taskmanager-15/blob/module-2/src/main.js#L16-L18)).

Если в своем проекте использовала суффикс `Element` в одном месте, то его следует добавить в названия других переменных, которые хранят DOM-элементы и внимательно следить за этим. Или отказаться от его использования, но тогда нужно в указанному месте убрать суффикс `Element`.

2021-08-13 14:30 UTC, ValeriaKhristinina commented on src/utils.js
> +  const newElement = document.createElement('div');
Всё, поняла!

2021-08-13 15:02 UTC, AlexMasterov requested changes

2021-08-14 13:05 UTC, ValeriaKhristinina commented on src/main.js
надеюсь все поправила

2021-08-14 13:50 UTC, merged