Module5 task1
htmlacademy-ecmascript/1791339-big-trip-15 pull request #7
Opened 2021-08-21 17:34 UTC by ValeriaKhristinina

2021-08-21 18:08 UTC, AlexMasterov requested changes

2021-08-21 18:08 UTC, AlexMasterov commented on src/presenter/point.js
> +export default class Point {
<details>
<summary>Point</summary>

https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/7b750b227b3051f4ca1fc9b461ba7bb1e6cc311d/src/presenter/point.js#L11
https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/7b750b227b3051f4ca1fc9b461ba7bb1e6cc311d/src/presenter/point.js#L28
https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/7b750b227b3051f4ca1fc9b461ba7bb1e6cc311d/src/presenter/point.js#L70
https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/7b750b227b3051f4ca1fc9b461ba7bb1e6cc311d/src/presenter/point.js#L76
</details>

`Point`._trip`Point`
**и т.п.**

[`Д 3`](https://up.htmlacademy.ru/ecmascript/15/criteries#d3)
> Название методов и свойств объектов не содержит [полное] название объектов

2021-08-21 18:08 UTC, AlexMasterov commented on src/presenter/trip.js
> +export default class Trip {
<details>
<summary>Trip</summary>

https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/7b750b227b3051f4ca1fc9b461ba7bb1e6cc311d/src/presenter/trip.js#L14
https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/7b750b227b3051f4ca1fc9b461ba7bb1e6cc311d/src/presenter/trip.js#L19-L22
https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/7b750b227b3051f4ca1fc9b461ba7bb1e6cc311d/src/presenter/trip.js#L24-L27
https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/7b750b227b3051f4ca1fc9b461ba7bb1e6cc311d/src/presenter/trip.js#L34-L35
https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/7b750b227b3051f4ca1fc9b461ba7bb1e6cc311d/src/presenter/trip.js#L56
https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/7b750b227b3051f4ca1fc9b461ba7bb1e6cc311d/src/presenter/trip.js#L63
https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/blob/7b750b227b3051f4ca1fc9b461ba7bb1e6cc311d/src/presenter/trip.js#L72
</details>

`Trip`._`trip`MainElement
**и т.п.**

[`Д 3`](https://up.htmlacademy.ru/ecmascript/15/criteries#d3)
> Название методов и свойств объектов не содержит [полное] название объектов

2021-08-23 07:56 UTC, AlexMasterov commented on src/utils/render.js
> -  const parent = oldChild.parentElement;
Было бы достаточно:
```diff
- const parent = oldChild.parentElement;
+ const parent = oldChild.parentElement || null;
```
😃

2021-08-23 07:58 UTC, ValeriaKhristinina commented on src/utils/render.js
> -  const parent = oldChild.parentElement;
сейчас переделаю))

2021-08-23 07:59 UTC, AlexMasterov commented on src/presenter/point.js
> +export default class Point {
Не вижу исправлений.

2021-08-23 07:59 UTC, AlexMasterov commented on src/presenter/trip.js
> +export default class Trip {
Не вижу исправлений.

2021-08-23 08:04 UTC, AlexMasterov commented
След. замечания нужно обязательно исправить при выполнении следующего задания.
https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/pull/7#discussion_r693383770
https://github.com/htmlacademy-ecmascript/1791339-big-trip-15/pull/7#discussion_r693383898

К ним легко придраться и это любят делать на защите проекта.

2021-08-23 08:04 UTC, merged